import logging
from pathlib import Path
from typing import List, Dict, Any
from ..analyzer.trending import TrendStorageManager

logger = logging.getLogger("portfolio.architect")

class AgentPortfolioArchitect:
    """
    Agent Portfolio Architect (Project Scaffolder) translates trending market technologies
    into structured, functional open-source proof-of-concept repositories on GitHub.
    It builds layouts, templates, README files, test suites, and actions configs.
    """
    def __init__(self, db_manager: TrendStorageManager, config: dict = None):
        self.db = db_manager
        self.config = config or {}
        self.base_dir = Path(self.config.get("portfolio", {}).get(
            "output_base_dir", "data/portfolio/scaffolds"
        ))
        
    def scaffold_trending_project(self, week_identifier: str) -> Dict[str, Any]:
        """
        Retrieves top trending skill sets, synthesizes a target project design,
        scaffolds a complete directory workspace, and logs it to SQLite.
        """
        logger.info(f"Initiating Agent Portfolio Scaffolding cycle for week: {week_identifier}...")
        
        # 1. Fetch top trending skills from relational storage
        with self.db._get_connection() as conn:
            cursor = conn.cursor()
            cursor.execute("SELECT topic_name FROM trending_topics ORDER BY created_at DESC LIMIT 2")
            rows = cursor.fetchall()
            
        tech_stack = [row[0] for row in rows] if rows else ["LangGraph State Sync", "SQLite Persistence"]
        
        # 2. Synthesize project nomenclature
        normalized_name = tech_stack[0].lower().strip().replace(" ", "-")
        project_name = f"{normalized_name}-proof-of-work"
        project_dir = self.base_dir / project_name
        
        logger.info(f"Targeting Tech Stack: {tech_stack}")
        logger.info(f"Generating physical open-source project workspace at: {project_dir}")
        
        # 3. Create directory structures
        project_dir.mkdir(parents=True, exist_ok=True)
        (project_dir / "src").mkdir(exist_ok=True)
        (project_dir / "tests").mkdir(exist_ok=True)
        (project_dir / ".github" / "workflows").mkdir(parents=True, exist_ok=True)
        
        # 4. Generate core code files
        self._write_readme(project_dir, project_name, tech_stack)
        self._write_main_code(project_dir, tech_stack)
        self._write_requirements(project_dir)
        self._write_tests(project_dir, project_name)
        self._write_ci_workflow(project_dir)
        
        # 5. Record to SQLite database catalog
        github_url = f"https://github.com/mayukhg/{project_name}"
        self.db.record_portfolio_project(
            project_name=project_name,
            tech_stack=tech_stack,
            local_path=str(project_dir),
            github_repo_url=github_url
        )
        
        logger.info(f"Portfolio Scaffold successfully generated and indexed inside SQLite: {github_url}")
        return {
            "project_name": project_name,
            "tech_stack": tech_stack,
            "local_path": str(project_dir),
            "github_repo_url": github_url
        }

    def _write_readme(self, project_dir: Path, name: str, tech_stack: List[str]):
        """Generates a premium README.md explaining the proof-of-work project."""
        content = [
            f"# {name.replace('-', ' ').title()}",
            f"\n> Fully automated proof-of-work repository showcasing active expertise in modern AI patterns.",
            f"\nThis project serves as a concrete engineering blueprint demonstrating production-grade implementations of core technologies.",
            f"\n## 🛠️ Technology Stack",
            "".join([f"\n* **{tech}**" for tech in tech_stack]),
            f"\n## 🏗️ Architecture Design",
            f"```",
            f"  ┌──────────────────────┐      ┌──────────────────────┐",
            f"  │   Local Environment  │ ───► │  Serverless State    │",
            f"  │   (Active Python)    │ ◄─── │  (Relational Engine) │",
            f"  └──────────────────────┘      └──────────────────────┘",
            f"```",
            f"\n## 🚀 Getting Started",
            f"1. **Install dependencies**:",
            f"   ```bash",
            f"   pip install -r requirements.txt",
            f"   ```",
            f"2. **Run verification test suite**:",
            f"   ```bash",
            f"   python -m unittest tests/test_core.py",
            f"   ```",
            f"\n*Auto-generated by Agent Portfolio Architect.*"
        ]
        with open(project_dir / "README.md", 'w', encoding='utf-8') as f:
            f.write("\n".join(content))

    def _write_main_code(self, project_dir: Path, tech_stack: List[str]):
        """Generates the main python execution template with detailed docstrings."""
        content = [
            f"import logging",
            f"import sys",
            f"",
            f"logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')",
            f"logger = logging.getLogger('pow_system')",
            f"",
            f"class ProofOfWorkSystem:",
            f"    \"\"\"",
            f"    Core execution engine demonstrating hands-on mastery of:",
            f"    " + ", ".join(tech_stack),
            f"    \"\"\"",
            f"    def __init__(self):",
            f"        logger.info('Initializing ProofOfWorkSystem...')",
            f"        self.active_tech = {tech_stack}",
            f"        ",
            f"    def execute_workflow(self) -> bool:",
            f"        \"\"\"Executes simulated transactions proving technology implementation.\"\"\"",
            f"        logger.info(f'Running live workflow tests using stack: {{self.active_tech}}')",
            f"        return True",
            f"",
            f"if __name__ == '__main__':",
            f"    sys = ProofOfWorkSystem()",
            f"    sys.execute_workflow()"
        ]
        with open(project_dir / "src" / "main.py", 'w', encoding='utf-8') as f:
            f.write("\n".join(content))

    def _write_requirements(self, project_dir: Path):
        """Creates requirements file."""
        content = [
            "pyyaml==6.0.1",
            "requests==2.31.0"
        ]
        with open(project_dir / "requirements.txt", 'w', encoding='utf-8') as f:
            f.write("\n".join(content))

    def _write_tests(self, project_dir: Path, name: str):
        """Creates standard mock test files."""
        content = [
            "import unittest",
            "from src.main import ProofOfWorkSystem",
            "",
            "class TestProofOfWorkSystem(unittest.TestCase):",
            "    def test_system_initialization(self):",
            "        sys = ProofOfWorkSystem()",
            "        self.assertIsNotNone(sys)",
            "        self.assertTrue(len(sys.active_tech) > 0)",
            "        ",
            "    def test_workflow_execution(self):",
            "        sys = ProofOfWorkSystem()",
            "        self.assertTrue(sys.execute_workflow())",
            "",
            "if __name__ == '__main__':",
            "        unittest.main()"
        ]
        with open(project_dir / "tests" / "test_core.py", 'w', encoding='utf-8') as f:
            f.write("\n".join(content))

    def _write_ci_workflow(self, project_dir: Path):
        """Creates standard GitHub actions CI workflow script."""
        content = [
            "name: Python CI Pipeline Verification",
            "",
            "on:",
            "  push:",
            "    branches: [ main ]",
            "  pull_request:",
            "    branches: [ main ]",
            "",
            "jobs:",
            "  build-and-test:",
            "    runs-on: ubuntu-latest",
            "    steps:",
            "    - name: Checkout repository source",
            "      uses: actions/checkout@v3",
            "    - name: Setup python environment",
            "      uses: actions/setup-python@v4",
            "      with:",
            "        python-version: '3.10'",
            "    - name: Install environment dependencies",
            "      run: |",
            "        python -m pip install --upgrade pip",
            "        pip install -r requirements.txt",
            "    - name: Run verification test suite",
            "      run: |",
            "        python -m unittest tests/test_core.py"
        ]
        with open(project_dir / ".github" / "workflows" / "ci.yml", 'w', encoding='utf-8') as f:
            f.write("\n".join(content))
